# Generated by Django 5.2.1 on 2025-05-24 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specjalizacja', models.CharField(max_length=100)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('pacjent', 'Pacjent'), ('lekarz', 'Lekarz')], default='pacjent', max_length=10)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina', models.TimeField()),
                ('dostepny', models.BooleanField(default=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracja.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='UsunKontoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc', models.TextField()),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('potwierdzone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WiadomoscOdLekarza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracja.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lekarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracja.lekarz')),
                ('pacjent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='rejestracja.profil')),
                ('termin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracja.termin')),
            ],
        ),
    ]
