# Generated by Django 5.2.1 on 2025-05-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizyta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='telefon',
        ),
        migrations.AddField(
            model_name='wizyta',
            name='pacjent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='rejestracja.profil'),
        ),
    ]
