# Generated by Django 5.2.1 on 2025-05-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0002_remove_wizyta_email_remove_wizyta_imie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomoscodlekarza',
            name='lekarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracja.lekarz'),
        ),
    ]
